[workspace]
members = ["events/*"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
aoc = { git = "https://github.com/evenfurther/aoc" }
aoc-build = { git = "https://github.com/evenfurther/aoc" }
eyre = "0.6.8"
rstest = "0.23.0"
