comment_width = 80
condense_wildcard_suffixes = true
edition = "2021"
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Crate"
max_width = 80
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
wrap_comments = true
tab_spaces = 2
hard_tabs = false
trailing_comma = "Vertical"
